import './styles/App.scss';

import { BrowserRouter, Routes, Route } from "react-router-dom";

import * as Pages from "./pages/index.js";

function App() {
  return (
    <div id="App">
      <BrowserRouter>
        <Routes>
          <Route path="/" element={<Pages.Home />}></Route>
          <Route path="/dsa_cracker" element={<Pages.DSA />}></Route>
          <Route path="/dsa_cracker/array" element={<Pages.Array />}></Route>
          <Route path="/dsa_cracker/matrix" element={<Pages.Matrix />}></Route>
          <Route path="/dsa_cracker/strings" element={<Pages.Strings />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting" element={<Pages.SearchingSorting />}></Route>
          <Route path="/dsa_cracker/linked_list" element={<Pages.LinkedList />}></Route>
          <Route path="/dsa_cracker/bit_manipulation" element={<Pages.BitManipulation />}></Route>
          <Route path="/dsa_cracker/greedy" element={<Pages.Greedy />}></Route>
          <Route path="/dsa_cracker/backtracking" element={<Pages.Backtracking />}></Route>
          <Route path="/dsa_cracker/dynamic_programming" element={<Pages.DynamicProgramming />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues" element={<Pages.StacksQueues />}></Route>
          <Route path="/dsa_cracker/binary_trees" element={<Pages.BinaryTrees />}></Route>
          <Route path="/dsa_cracker/binary_search_tree" element={<Pages.BinarySearchTree />}></Route>
          <Route path="/dsa_cracker/graphs" element={<Pages.Graphs />}></Route>
          <Route path="/dsa_cracker/heap" element={<Pages.Heap />}></Route>
          <Route path="/dsa_cracker/trie" element={<Pages.Trie />}></Route>
          <Route path="/dsa_cracker/array/array_01" element={<Pages.Array01 />}></Route>
          <Route path="/dsa_cracker/array/array_02" element={<Pages.Array02 />}></Route>
          <Route path="/dsa_cracker/array/array_03" element={<Pages.Array03 />}></Route>
          <Route path="/dsa_cracker/array/array_04" element={<Pages.Array04 />}></Route>
          <Route path="/dsa_cracker/array/array_05" element={<Pages.Array05 />}></Route>
          <Route path="/dsa_cracker/array/array_06" element={<Pages.Array06 />}></Route>
          <Route path="/dsa_cracker/array/array_07" element={<Pages.Array07 />}></Route>
          <Route path="/dsa_cracker/array/array_08" element={<Pages.Array08 />}></Route>
          <Route path="/dsa_cracker/array/array_09" element={<Pages.Array09 />}></Route>
          <Route path="/dsa_cracker/array/array_10" element={<Pages.Array10 />}></Route>
          <Route path="/dsa_cracker/array/array_11" element={<Pages.Array11 />}></Route>
          <Route path="/dsa_cracker/array/array_12" element={<Pages.Array12 />}></Route>
          <Route path="/dsa_cracker/array/array_13" element={<Pages.Array13 />}></Route>
          <Route path="/dsa_cracker/array/array_14" element={<Pages.Array14 />}></Route>
          <Route path="/dsa_cracker/array/array_15" element={<Pages.Array15 />}></Route>
          <Route path="/dsa_cracker/array/array_16" element={<Pages.Array16 />}></Route>
          <Route path="/dsa_cracker/array/array_17" element={<Pages.Array17 />}></Route>
          <Route path="/dsa_cracker/array/array_18" element={<Pages.Array18 />}></Route>
          <Route path="/dsa_cracker/array/array_19" element={<Pages.Array19 />}></Route>
          <Route path="/dsa_cracker/array/array_20" element={<Pages.Array20 />}></Route>
          <Route path="/dsa_cracker/array/array_21" element={<Pages.Array21 />}></Route>
          <Route path="/dsa_cracker/array/array_22" element={<Pages.Array22 />}></Route>
          <Route path="/dsa_cracker/array/array_23" element={<Pages.Array23 />}></Route>
          <Route path="/dsa_cracker/array/array_24" element={<Pages.Array24 />}></Route>
          <Route path="/dsa_cracker/array/array_25" element={<Pages.Array25 />}></Route>
          <Route path="/dsa_cracker/array/array_26" element={<Pages.Array26 />}></Route>
          <Route path="/dsa_cracker/array/array_27" element={<Pages.Array27 />}></Route>
          <Route path="/dsa_cracker/array/array_28" element={<Pages.Array28 />}></Route>
          <Route path="/dsa_cracker/array/array_29" element={<Pages.Array29 />}></Route>
          <Route path="/dsa_cracker/array/array_30" element={<Pages.Array30 />}></Route>
          <Route path="/dsa_cracker/array/array_31" element={<Pages.Array31 />}></Route>
          <Route path="/dsa_cracker/array/array_32" element={<Pages.Array32 />}></Route>
          <Route path="/dsa_cracker/array/array_33" element={<Pages.Array33 />}></Route>
          <Route path="/dsa_cracker/array/array_34" element={<Pages.Array34 />}></Route>
          <Route path="/dsa_cracker/array/array_35" element={<Pages.Array35 />}></Route>
          <Route path="/dsa_cracker/array/array_36" element={<Pages.Array36 />}></Route>
          <Route path="/dsa_cracker/matrix/matrix_01" element={<Pages.Matrix01 />}></Route>
          <Route path="/dsa_cracker/matrix/matrix_02" element={<Pages.Matrix02 />}></Route>
          <Route path="/dsa_cracker/matrix/matrix_03" element={<Pages.Matrix03 />}></Route>
          <Route path="/dsa_cracker/matrix/matrix_04" element={<Pages.Matrix04 />}></Route>
          <Route path="/dsa_cracker/matrix/matrix_05" element={<Pages.Matrix05 />}></Route>
          <Route path="/dsa_cracker/matrix/matrix_06" element={<Pages.Matrix06 />}></Route>
          <Route path="/dsa_cracker/matrix/matrix_07" element={<Pages.Matrix07 />}></Route>
          <Route path="/dsa_cracker/matrix/matrix_08" element={<Pages.Matrix08 />}></Route>
          <Route path="/dsa_cracker/matrix/matrix_09" element={<Pages.Matrix09 />}></Route>
          <Route path="/dsa_cracker/matrix/matrix_10" element={<Pages.Matrix10 />}></Route>
          {/* <Route path="/dsa_cracker/strings/strings_01" element={<Pages.Strings01 />}></Route>
          <Route path="/dsa_cracker/strings/strings_02" element={<Pages.Strings02 />}></Route>
          <Route path="/dsa_cracker/strings/strings_03" element={<Pages.Strings03 />}></Route>
          <Route path="/dsa_cracker/strings/strings_04" element={<Pages.Strings04 />}></Route>
          <Route path="/dsa_cracker/strings/strings_05" element={<Pages.Strings05 />}></Route>
          <Route path="/dsa_cracker/strings/strings_06" element={<Pages.Strings06 />}></Route>
          <Route path="/dsa_cracker/strings/strings_07" element={<Pages.Strings07 />}></Route>
          <Route path="/dsa_cracker/strings/strings_08" element={<Pages.Strings08 />}></Route>
          <Route path="/dsa_cracker/strings/strings_09" element={<Pages.Strings09 />}></Route>
          <Route path="/dsa_cracker/strings/strings_10" element={<Pages.Strings10 />}></Route>
          <Route path="/dsa_cracker/strings/strings_11" element={<Pages.Strings11 />}></Route>
          <Route path="/dsa_cracker/strings/strings_12" element={<Pages.Strings12 />}></Route>
          <Route path="/dsa_cracker/strings/strings_13" element={<Pages.Strings13 />}></Route>
          <Route path="/dsa_cracker/strings/strings_14" element={<Pages.Strings14 />}></Route>
          <Route path="/dsa_cracker/strings/strings_15" element={<Pages.Strings15 />}></Route>
          <Route path="/dsa_cracker/strings/strings_16" element={<Pages.Strings16 />}></Route>
          <Route path="/dsa_cracker/strings/strings_17" element={<Pages.Strings17 />}></Route>
          <Route path="/dsa_cracker/strings/strings_18" element={<Pages.Strings18 />}></Route>
          <Route path="/dsa_cracker/strings/strings_19" element={<Pages.Strings19 />}></Route>
          <Route path="/dsa_cracker/strings/strings_20" element={<Pages.Strings20 />}></Route>
          <Route path="/dsa_cracker/strings/strings_21" element={<Pages.Strings21 />}></Route>
          <Route path="/dsa_cracker/strings/strings_22" element={<Pages.Strings22 />}></Route>
          <Route path="/dsa_cracker/strings/strings_23" element={<Pages.Strings23 />}></Route>
          <Route path="/dsa_cracker/strings/strings_24" element={<Pages.Strings24 />}></Route>
          <Route path="/dsa_cracker/strings/strings_25" element={<Pages.Strings25 />}></Route>
          <Route path="/dsa_cracker/strings/strings_26" element={<Pages.Strings26 />}></Route>
          <Route path="/dsa_cracker/strings/strings_27" element={<Pages.Strings27 />}></Route>
          <Route path="/dsa_cracker/strings/strings_28" element={<Pages.Strings28 />}></Route>
          <Route path="/dsa_cracker/strings/strings_29" element={<Pages.Strings29 />}></Route>
          <Route path="/dsa_cracker/strings/strings_30" element={<Pages.Strings30 />}></Route>
          <Route path="/dsa_cracker/strings/strings_31" element={<Pages.Strings31 />}></Route>
          <Route path="/dsa_cracker/strings/strings_32" element={<Pages.Strings32 />}></Route>
          <Route path="/dsa_cracker/strings/strings_33" element={<Pages.Strings33 />}></Route>
          <Route path="/dsa_cracker/strings/strings_34" element={<Pages.Strings34 />}></Route>
          <Route path="/dsa_cracker/strings/strings_35" element={<Pages.Strings35 />}></Route>
          <Route path="/dsa_cracker/strings/strings_36" element={<Pages.Strings36 />}></Route>
          <Route path="/dsa_cracker/strings/strings_37" element={<Pages.Strings37 />}></Route>
          <Route path="/dsa_cracker/strings/strings_38" element={<Pages.Strings38 />}></Route>
          <Route path="/dsa_cracker/strings/strings_39" element={<Pages.Strings39 />}></Route>
          <Route path="/dsa_cracker/strings/strings_40" element={<Pages.Strings40 />}></Route>
          <Route path="/dsa_cracker/strings/strings_41" element={<Pages.Strings41 />}></Route>
          <Route path="/dsa_cracker/strings/strings_42" element={<Pages.Strings42 />}></Route>
          <Route path="/dsa_cracker/strings/strings_43" element={<Pages.Strings43 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_01" element={<Pages.SearchingSorting01 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_02" element={<Pages.SearchingSorting02 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_03" element={<Pages.SearchingSorting03 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_04" element={<Pages.SearchingSorting04 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_05" element={<Pages.SearchingSorting05 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_06" element={<Pages.SearchingSorting06 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_07" element={<Pages.SearchingSorting07 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_08" element={<Pages.SearchingSorting08 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_09" element={<Pages.SearchingSorting09 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_10" element={<Pages.SearchingSorting10 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_11" element={<Pages.SearchingSorting11 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_12" element={<Pages.SearchingSorting12 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_13" element={<Pages.SearchingSorting13 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_14" element={<Pages.SearchingSorting14 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_15" element={<Pages.SearchingSorting15 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_16" element={<Pages.SearchingSorting16 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_17" element={<Pages.SearchingSorting17 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_18" element={<Pages.SearchingSorting18 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_19" element={<Pages.SearchingSorting19 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_20" element={<Pages.SearchingSorting20 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_21" element={<Pages.SearchingSorting21 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_22" element={<Pages.SearchingSorting22 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_23" element={<Pages.SearchingSorting23 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_24" element={<Pages.SearchingSorting24 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_25" element={<Pages.SearchingSorting25 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_26" element={<Pages.SearchingSorting26 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_27" element={<Pages.SearchingSorting27 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_28" element={<Pages.SearchingSorting28 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_29" element={<Pages.SearchingSorting29 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_30" element={<Pages.SearchingSorting30 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_31" element={<Pages.SearchingSorting31 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_32" element={<Pages.SearchingSorting32 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_33" element={<Pages.SearchingSorting33 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_34" element={<Pages.SearchingSorting34 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_35" element={<Pages.SearchingSorting35 />}></Route>
          <Route path="/dsa_cracker/searching_and_sorting/searching_and_sorting_36" element={<Pages.SearchingSorting36 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_01" element={<Pages.LinkedList01 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_02" element={<Pages.LinkedList02 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_03" element={<Pages.LinkedList03 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_04" element={<Pages.LinkedList04 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_05" element={<Pages.LinkedList05 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_06" element={<Pages.LinkedList06 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_07" element={<Pages.LinkedList07 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_08" element={<Pages.LinkedList08 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_09" element={<Pages.LinkedList09 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_10" element={<Pages.LinkedList10 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_11" element={<Pages.LinkedList11 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_12" element={<Pages.LinkedList12 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_13" element={<Pages.LinkedList13 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_14" element={<Pages.LinkedList14 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_15" element={<Pages.LinkedList15 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_16" element={<Pages.LinkedList16 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_17" element={<Pages.LinkedList17 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_18" element={<Pages.LinkedList18 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_19" element={<Pages.LinkedList19 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_20" element={<Pages.LinkedList20 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_21" element={<Pages.LinkedList21 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_22" element={<Pages.LinkedList22 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_23" element={<Pages.LinkedList23 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_24" element={<Pages.LinkedList24 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_25" element={<Pages.LinkedList25 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_26" element={<Pages.LinkedList26 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_27" element={<Pages.LinkedList27 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_28" element={<Pages.LinkedList28 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_29" element={<Pages.LinkedList29 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_30" element={<Pages.LinkedList30 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_31" element={<Pages.LinkedList31 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_32" element={<Pages.LinkedList32 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_33" element={<Pages.LinkedList33 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_34" element={<Pages.LinkedList34 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_35" element={<Pages.LinkedList35 />}></Route>
          <Route path="/dsa_cracker/linked_list/linked_list_36" element={<Pages.LinkedList36 />}></Route> */}
          <Route path="/dsa_cracker/bit_manipulation/bit_manipulation_01" element={<Pages.BitManipulation01 />}></Route>
          <Route path="/dsa_cracker/bit_manipulation/bit_manipulation_02" element={<Pages.BitManipulation02 />}></Route>
          <Route path="/dsa_cracker/bit_manipulation/bit_manipulation_03" element={<Pages.BitManipulation03 />}></Route>
          <Route path="/dsa_cracker/bit_manipulation/bit_manipulation_04" element={<Pages.BitManipulation04 />}></Route>
          <Route path="/dsa_cracker/bit_manipulation/bit_manipulation_05" element={<Pages.BitManipulation05 />}></Route>
          <Route path="/dsa_cracker/bit_manipulation/bit_manipulation_06" element={<Pages.BitManipulation06 />}></Route>
          <Route path="/dsa_cracker/bit_manipulation/bit_manipulation_07" element={<Pages.BitManipulation07 />}></Route>
          <Route path="/dsa_cracker/bit_manipulation/bit_manipulation_08" element={<Pages.BitManipulation08 />}></Route>
          <Route path="/dsa_cracker/bit_manipulation/bit_manipulation_09" element={<Pages.BitManipulation09 />}></Route>
          <Route path="/dsa_cracker/bit_manipulation/bit_manipulation_10" element={<Pages.BitManipulation10 />}></Route>
          {/*<Route path="/dsa_cracker/greedy/greedy_01" element={<Pages.Greedy01 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_02" element={<Pages.Greedy02 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_03" element={<Pages.Greedy03 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_04" element={<Pages.Greedy04 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_05" element={<Pages.Greedy05 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_06" element={<Pages.Greedy06 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_07" element={<Pages.Greedy07 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_08" element={<Pages.Greedy08 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_09" element={<Pages.Greedy09 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_10" element={<Pages.Greedy10 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_11" element={<Pages.Greedy11 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_12" element={<Pages.Greedy12 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_13" element={<Pages.Greedy13 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_14" element={<Pages.Greedy14 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_15" element={<Pages.Greedy15 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_16" element={<Pages.Greedy16 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_17" element={<Pages.Greedy17 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_18" element={<Pages.Greedy18 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_19" element={<Pages.Greedy19 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_20" element={<Pages.Greedy20 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_21" element={<Pages.Greedy21 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_22" element={<Pages.Greedy22 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_23" element={<Pages.Greedy23 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_24" element={<Pages.Greedy24 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_25" element={<Pages.Greedy25 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_26" element={<Pages.Greedy26 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_27" element={<Pages.Greedy27 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_28" element={<Pages.Greedy28 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_29" element={<Pages.Greedy29 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_30" element={<Pages.Greedy30 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_31" element={<Pages.Greedy31 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_32" element={<Pages.Greedy32 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_33" element={<Pages.Greedy33 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_34" element={<Pages.Greedy34 />}></Route>
          <Route path="/dsa_cracker/greedy/greedy_35" element={<Pages.Greedy35 />}></Route>
          <Route path="/dsa_cracker/backtracking/backtracking_01" element={<Pages.Backtracking01 />}></Route>
          <Route path="/dsa_cracker/backtracking/backtracking_02" element={<Pages.Backtracking02 />}></Route>
          <Route path="/dsa_cracker/backtracking/backtracking_03" element={<Pages.Backtracking03 />}></Route>
          <Route path="/dsa_cracker/backtracking/backtracking_04" element={<Pages.Backtracking04 />}></Route>
          <Route path="/dsa_cracker/backtracking/backtracking_05" element={<Pages.Backtracking05 />}></Route>
          <Route path="/dsa_cracker/backtracking/backtracking_06" element={<Pages.Backtracking06 />}></Route>
          <Route path="/dsa_cracker/backtracking/backtracking_07" element={<Pages.Backtracking07 />}></Route>
          <Route path="/dsa_cracker/backtracking/backtracking_08" element={<Pages.Backtracking08 />}></Route>
          <Route path="/dsa_cracker/backtracking/backtracking_09" element={<Pages.Backtracking09 />}></Route>
          <Route path="/dsa_cracker/backtracking/backtracking_10" element={<Pages.Backtracking10 />}></Route>
          <Route path="/dsa_cracker/backtracking/backtracking_11" element={<Pages.Backtracking11 />}></Route>
          <Route path="/dsa_cracker/backtracking/backtracking_12" element={<Pages.Backtracking12 />}></Route>
          <Route path="/dsa_cracker/backtracking/backtracking_13" element={<Pages.Backtracking13 />}></Route>
          <Route path="/dsa_cracker/backtracking/backtracking_14" element={<Pages.Backtracking14 />}></Route>
          <Route path="/dsa_cracker/backtracking/backtracking_15" element={<Pages.Backtracking15 />}></Route>
          <Route path="/dsa_cracker/backtracking/backtracking_16" element={<Pages.Backtracking16 />}></Route>
          <Route path="/dsa_cracker/backtracking/backtracking_17" element={<Pages.Backtracking17 />}></Route>
          <Route path="/dsa_cracker/backtracking/backtracking_18" element={<Pages.Backtracking18 />}></Route>
          <Route path="/dsa_cracker/backtracking/backtracking_19" element={<Pages.Backtracking19 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_01" element={<Pages.DynamicProgramming01 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_02" element={<Pages.DynamicProgramming02 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_03" element={<Pages.DynamicProgramming03 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_04" element={<Pages.DynamicProgramming04 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_05" element={<Pages.DynamicProgramming05 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_06" element={<Pages.DynamicProgramming06 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_07" element={<Pages.DynamicProgramming07 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_08" element={<Pages.DynamicProgramming08 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_09" element={<Pages.DynamicProgramming09 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_10" element={<Pages.DynamicProgramming10 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_11" element={<Pages.DynamicProgramming11 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_12" element={<Pages.DynamicProgramming12 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_13" element={<Pages.DynamicProgramming13 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_14" element={<Pages.DynamicProgramming14 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_15" element={<Pages.DynamicProgramming15 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_16" element={<Pages.DynamicProgramming16 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_17" element={<Pages.DynamicProgramming17 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_18" element={<Pages.DynamicProgramming18 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_19" element={<Pages.DynamicProgramming19 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_20" element={<Pages.DynamicProgramming20 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_21" element={<Pages.DynamicProgramming21 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_22" element={<Pages.DynamicProgramming22 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_23" element={<Pages.DynamicProgramming23 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_24" element={<Pages.DynamicProgramming24 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_25" element={<Pages.DynamicProgramming25 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_26" element={<Pages.DynamicProgramming26 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_27" element={<Pages.DynamicProgramming27 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_28" element={<Pages.DynamicProgramming28 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_29" element={<Pages.DynamicProgramming29 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_30" element={<Pages.DynamicProgramming30 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_31" element={<Pages.DynamicProgramming31 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_32" element={<Pages.DynamicProgramming32 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_33" element={<Pages.DynamicProgramming33 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_34" element={<Pages.DynamicProgramming34 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_35" element={<Pages.DynamicProgramming35 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_36" element={<Pages.DynamicProgramming36 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_37" element={<Pages.DynamicProgramming37 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_38" element={<Pages.DynamicProgramming38 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_39" element={<Pages.DynamicProgramming39 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_40" element={<Pages.DynamicProgramming40 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_41" element={<Pages.DynamicProgramming41 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_42" element={<Pages.DynamicProgramming42 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_43" element={<Pages.DynamicProgramming43 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_44" element={<Pages.DynamicProgramming44 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_45" element={<Pages.DynamicProgramming45 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_46" element={<Pages.DynamicProgramming46 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_47" element={<Pages.DynamicProgramming47 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_48" element={<Pages.DynamicProgramming48 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_49" element={<Pages.DynamicProgramming49 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_50" element={<Pages.DynamicProgramming50 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_51" element={<Pages.DynamicProgramming51 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_52" element={<Pages.DynamicProgramming52 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_53" element={<Pages.DynamicProgramming53 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_54" element={<Pages.DynamicProgramming54 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_55" element={<Pages.DynamicProgramming55 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_56" element={<Pages.DynamicProgramming56 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_57" element={<Pages.DynamicProgramming57 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_58" element={<Pages.DynamicProgramming58 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_59" element={<Pages.DynamicProgramming59 />}></Route>
          <Route path="/dsa_cracker/dynamic_programming/dynamic_programming_60" element={<Pages.DynamicProgramming60 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_01" element={<Pages.StacksQueues01 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_02" element={<Pages.StacksQueues02 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_03" element={<Pages.StacksQueues03 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_04" element={<Pages.StacksQueues04 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_05" element={<Pages.StacksQueues05 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_06" element={<Pages.StacksQueues06 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_07" element={<Pages.StacksQueues07 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_08" element={<Pages.StacksQueues08 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_09" element={<Pages.StacksQueues09 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_10" element={<Pages.StacksQueues10 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_11" element={<Pages.StacksQueues11 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_12" element={<Pages.StacksQueues12 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_13" element={<Pages.StacksQueues13 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_14" element={<Pages.StacksQueues14 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_15" element={<Pages.StacksQueues15 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_16" element={<Pages.StacksQueues16 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_17" element={<Pages.StacksQueues17 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_18" element={<Pages.StacksQueues18 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_19" element={<Pages.StacksQueues19 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_20" element={<Pages.StacksQueues20 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_21" element={<Pages.StacksQueues21 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_22" element={<Pages.StacksQueues22 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_23" element={<Pages.StacksQueues23 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_24" element={<Pages.StacksQueues24 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_25" element={<Pages.StacksQueues25 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_26" element={<Pages.StacksQueues26 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_27" element={<Pages.StacksQueues27 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_28" element={<Pages.StacksQueues28 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_29" element={<Pages.StacksQueues29 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_30" element={<Pages.StacksQueues30 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_31" element={<Pages.StacksQueues31 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_32" element={<Pages.StacksQueues32 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_33" element={<Pages.StacksQueues33 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_34" element={<Pages.StacksQueues34 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_35" element={<Pages.StacksQueues35 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_36" element={<Pages.StacksQueues36 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_37" element={<Pages.StacksQueues37 />}></Route>
          <Route path="/dsa_cracker/stacks_and_queues/stacks_and_queues_38" element={<Pages.StacksQueues38 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_01" element={<Pages.BinaryTrees01 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_02" element={<Pages.BinaryTrees02 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_03" element={<Pages.BinaryTrees03 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_04" element={<Pages.BinaryTrees04 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_05" element={<Pages.BinaryTrees05 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_06" element={<Pages.BinaryTrees06 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_07" element={<Pages.BinaryTrees07 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_08" element={<Pages.BinaryTrees08 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_09" element={<Pages.BinaryTrees09 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_10" element={<Pages.BinaryTrees10 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_11" element={<Pages.BinaryTrees11 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_12" element={<Pages.BinaryTrees12 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_13" element={<Pages.BinaryTrees13 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_14" element={<Pages.BinaryTrees14 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_15" element={<Pages.BinaryTrees15 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_16" element={<Pages.BinaryTrees16 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_17" element={<Pages.BinaryTrees17 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_18" element={<Pages.BinaryTrees18 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_19" element={<Pages.BinaryTrees19 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_20" element={<Pages.BinaryTrees20 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_21" element={<Pages.BinaryTrees21 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_22" element={<Pages.BinaryTrees22 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_23" element={<Pages.BinaryTrees23 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_24" element={<Pages.BinaryTrees24 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_25" element={<Pages.BinaryTrees25 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_26" element={<Pages.BinaryTrees26 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_27" element={<Pages.BinaryTrees27 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_28" element={<Pages.BinaryTrees28 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_29" element={<Pages.BinaryTrees29 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_30" element={<Pages.BinaryTrees30 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_31" element={<Pages.BinaryTrees31 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_32" element={<Pages.BinaryTrees32 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_33" element={<Pages.BinaryTrees33 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_34" element={<Pages.BinaryTrees34 />}></Route>
          <Route path="/dsa_cracker/binary_trees/binary_trees_35" element={<Pages.BinaryTrees35 />}></Route>
          <Route path="/dsa_cracker/binary_search_tree/binary_search_tree_01" element={<Pages.BinarySearchTree01 />}></Route>
          <Route path="/dsa_cracker/binary_search_tree/binary_search_tree_02" element={<Pages.BinarySearchTree02 />}></Route>
          <Route path="/dsa_cracker/binary_search_tree/binary_search_tree_03" element={<Pages.BinarySearchTree03 />}></Route>
          <Route path="/dsa_cracker/binary_search_tree/binary_search_tree_04" element={<Pages.BinarySearchTree04 />}></Route>
          <Route path="/dsa_cracker/binary_search_tree/binary_search_tree_05" element={<Pages.BinarySearchTree05 />}></Route>
          <Route path="/dsa_cracker/binary_search_tree/binary_search_tree_06" element={<Pages.BinarySearchTree06 />}></Route>
          <Route path="/dsa_cracker/binary_search_tree/binary_search_tree_07" element={<Pages.BinarySearchTree07 />}></Route>
          <Route path="/dsa_cracker/binary_search_tree/binary_search_tree_08" element={<Pages.BinarySearchTree08 />}></Route>
          <Route path="/dsa_cracker/binary_search_tree/binary_search_tree_09" element={<Pages.BinarySearchTree09 />}></Route>
          <Route path="/dsa_cracker/binary_search_tree/binary_search_tree_10" element={<Pages.BinarySearchTree10 />}></Route>
          <Route path="/dsa_cracker/binary_search_tree/binary_search_tree_11" element={<Pages.BinarySearchTree11 />}></Route>
          <Route path="/dsa_cracker/binary_search_tree/binary_search_tree_12" element={<Pages.BinarySearchTree12 />}></Route>
          <Route path="/dsa_cracker/binary_search_tree/binary_search_tree_13" element={<Pages.BinarySearchTree13 />}></Route>
          <Route path="/dsa_cracker/binary_search_tree/binary_search_tree_14" element={<Pages.BinarySearchTree14 />}></Route>
          <Route path="/dsa_cracker/binary_search_tree/binary_search_tree_15" element={<Pages.BinarySearchTree15 />}></Route>
          <Route path="/dsa_cracker/binary_search_tree/binary_search_tree_16" element={<Pages.BinarySearchTree16 />}></Route>
          <Route path="/dsa_cracker/binary_search_tree/binary_search_tree_17" element={<Pages.BinarySearchTree17 />}></Route>
          <Route path="/dsa_cracker/binary_search_tree/binary_search_tree_18" element={<Pages.BinarySearchTree18 />}></Route>
          <Route path="/dsa_cracker/binary_search_tree/binary_search_tree_19" element={<Pages.BinarySearchTree19 />}></Route>
          <Route path="/dsa_cracker/binary_search_tree/binary_search_tree_20" element={<Pages.BinarySearchTree20 />}></Route>
          <Route path="/dsa_cracker/binary_search_tree/binary_search_tree_21" element={<Pages.BinarySearchTree21 />}></Route>
          <Route path="/dsa_cracker/binary_search_tree/binary_search_tree_22" element={<Pages.BinarySearchTree22 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_01" element={<Pages.Graphs01 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_02" element={<Pages.Graphs02 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_03" element={<Pages.Graphs03 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_04" element={<Pages.Graphs04 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_05" element={<Pages.Graphs05 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_06" element={<Pages.Graphs06 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_07" element={<Pages.Graphs07 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_08" element={<Pages.Graphs08 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_09" element={<Pages.Graphs09 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_10" element={<Pages.Graphs10 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_11" element={<Pages.Graphs11 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_12" element={<Pages.Graphs12 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_13" element={<Pages.Graphs13 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_14" element={<Pages.Graphs14 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_15" element={<Pages.Graphs15 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_16" element={<Pages.Graphs16 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_17" element={<Pages.Graphs17 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_18" element={<Pages.Graphs18 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_19" element={<Pages.Graphs19 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_20" element={<Pages.Graphs20 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_21" element={<Pages.Graphs21 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_22" element={<Pages.Graphs22 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_23" element={<Pages.Graphs23 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_24" element={<Pages.Graphs24 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_25" element={<Pages.Graphs25 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_26" element={<Pages.Graphs26 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_27" element={<Pages.Graphs27 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_28" element={<Pages.Graphs28 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_29" element={<Pages.Graphs29 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_30" element={<Pages.Graphs30 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_31" element={<Pages.Graphs31 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_32" element={<Pages.Graphs32 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_33" element={<Pages.Graphs33 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_34" element={<Pages.Graphs34 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_35" element={<Pages.Graphs35 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_36" element={<Pages.Graphs36 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_37" element={<Pages.Graphs37 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_38" element={<Pages.Graphs38 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_39" element={<Pages.Graphs39 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_40" element={<Pages.Graphs40 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_41" element={<Pages.Graphs41 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_42" element={<Pages.Graphs42 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_43" element={<Pages.Graphs43 />}></Route>
          <Route path="/dsa_cracker/graphs/graphs_44" element={<Pages.Graphs44 />}></Route>
          <Route path="/dsa_cracker/heap/heap_01" element={<Pages.Heap01 />}></Route>
          <Route path="/dsa_cracker/heap/heap_02" element={<Pages.Heap02 />}></Route>
          <Route path="/dsa_cracker/heap/heap_03" element={<Pages.Heap03 />}></Route>
          <Route path="/dsa_cracker/heap/heap_04" element={<Pages.Heap04 />}></Route>
          <Route path="/dsa_cracker/heap/heap_05" element={<Pages.Heap05 />}></Route>
          <Route path="/dsa_cracker/heap/heap_06" element={<Pages.Heap06 />}></Route>
          <Route path="/dsa_cracker/heap/heap_07" element={<Pages.Heap07 />}></Route>
          <Route path="/dsa_cracker/heap/heap_08" element={<Pages.Heap08 />}></Route>
          <Route path="/dsa_cracker/heap/heap_09" element={<Pages.Heap09 />}></Route>
          <Route path="/dsa_cracker/heap/heap_10" element={<Pages.Heap10 />}></Route>
          <Route path="/dsa_cracker/heap/heap_11" element={<Pages.Heap11 />}></Route>
          <Route path="/dsa_cracker/heap/heap_12" element={<Pages.Heap12 />}></Route>
          <Route path="/dsa_cracker/heap/heap_13" element={<Pages.Heap13 />}></Route>
          <Route path="/dsa_cracker/heap/heap_14" element={<Pages.Heap14 />}></Route>
          <Route path="/dsa_cracker/heap/heap_15" element={<Pages.Heap15 />}></Route>
          <Route path="/dsa_cracker/heap/heap_16" element={<Pages.Heap16 />}></Route>
          <Route path="/dsa_cracker/heap/heap_17" element={<Pages.Heap17 />}></Route>
          <Route path="/dsa_cracker/heap/heap_18" element={<Pages.Heap18 />}></Route> */}
          <Route path="/dsa_cracker/trie/trie_01" element={<Pages.Trie01 />}></Route>
          <Route path="/dsa_cracker/trie/trie_02" element={<Pages.Trie02 />}></Route>
          <Route path="/dsa_cracker/trie/trie_03" element={<Pages.Trie03 />}></Route>
          <Route path="/dsa_cracker/trie/trie_04" element={<Pages.Trie04 />}></Route>
          <Route path="/dsa_cracker/trie/trie_05" element={<Pages.Trie05 />}></Route>
          <Route path="/dsa_cracker/trie/trie_06" element={<Pages.Trie06 />}></Route>
        </Routes>
      </BrowserRouter>
    </div>
  );
}

export default App;
